### ISSUE TITLE
Stop output when running demo mode

### ISSUE THREAD

**Issue by DPCau** [OSU-NLP-Group/SeeAct#59]
This is the output of terminal
```zsh
(seeact) xxxxxx@xxx src % python seeact.py
Configuration File Loaded - /Users/xxxxxx/MyProject/SeeAct/src/config/demo_mode.toml
Please input a task, and press Enter. 
Or directly press Enter to use the default task: Find pdf of paper "GPT-4V(ision) is a Generalist Web Agent, if Grounded" from arXiv
Task: 
Please input the complete URL of the starting website, and press Enter. The URL must be complete (for example, including http), to ensure the browser can successfully load the webpage. 
Or directly press Enter to use the default website: https://www.google.com/
Website: 
website: https://www.google.com/
task: Find pdf of paper "GPT-4V(ision) is a Generalist Web Agent, if Grounded" from arXiv
id: 2025-02-19_11-05-05
==========
Time step: 0
----------
# all elements: 18
batch size: 18
----------
You are asked to complete the following task: Find pdf of paper "GPT-4V(ision) is a Generalist Web Agent, if Grounded" from arXiv
Previous Actions:
None
----------
Start Multi-Choice QA - Batch 0
```
and it freeze there, despite I press `enter` or `Y`
when checking the process, it did not occupy much

by the way, I use gemini api which is to compatible with the OpenAI() module
```toml
[openai]
# You can find your API key at https://platform.openai.com/account/api-keys.
rate_limit = -1 # Rate limit for API calls (-1 for no limit).
#model = "gpt-4-vision-preview" # Model name, indicating the use of GPT-4 with vision capabilities.
model = "gemini-1.5-flash"
api_key = "MYGEMINIAPI"
temperature = 0 # Temperature setting for GPT's responses, controlling randomness.
```
in `inference_engin.py`, I add one line to change base_url referring to https://ai.google.dev/gemini-api/docs/openai
```py
    def generate(self, prompt: list = None, max_new_tokens=4096, temperature=None, model=None, image_path=None,
                 ouput__0=None, turn_number=0, **kwargs):
        self.current_key_idx = (self.current_key_idx + 1) % len(self.api_keys)
        start_time = time.time()
        if (
                self.request_interval > 0
                and start_time < self.next_avil_time[self.current_key_idx]
        ):
            time.sleep(self.next_avil_time[self.current_key_idx] - start_time)
        openai.api_key = self.api_keys[self.current_key_idx]
        # add this line
        openai.api_base = "https://generativelanguage.googleapis.com/v1beta/openai/"

        prompt0 = prompt[0]
        prompt1 = prompt[1]
        prompt2 = prompt[2]
```
